### ISSUE TITLE
[PE-D][Tester B] edit command tag 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-1/tp#100]
![Screenshot 2024-04-05 at 4.34.57 PM.png](https://raw.githubusercontent.com/DingBao-sys/ped/main/files/dd89031b-5736-47be-84d7-cab5019257e8.png)

UG specifies that tags should use alphanumeric and spaces, but when separated but multiple spaces the command does not accept the arguments

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: DingBao-sys/ped#4

**Comment by shawnnlimm** [comment]
Duplicate with #93
