### ISSUE TITLE
[PE-D][Tester D] UG Filter Fields Table Missing Parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-1/tp#125]
The Fields table under the filter feature is missing the `NUMBER_OF_TAGS` parameter, even though it is shown in the command format and example.

![image.png](https://raw.githubusercontent.com/getsquared/ped/main/files/dd249211-3427-474d-8296-f3cb0dfad94e.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: getsquared/ped#8

**Comment by shawnnlimm** [comment]
Duplicate of #96
