### ISSUE TITLE
[PE-D][Tester D] Grade Error Message Command Format Missing Parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-1/tp#136]
The error message for `grade` command is missing the `INDEX` and `SCORE` parameters. There is also a minor typo, `for one students` could be singular, `for one student`?

![image.png](https://raw.githubusercontent.com/getsquared/ped/main/files/dd616b82-5551-40b3-8aae-c1439111998c.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: getsquared/ped#17

**Comment by Ryo-Seah** [comment]
bug fixed - correct parameters added,  typo fixed
